[package]
name = "discord-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
better-panic = "0.3.0"
clap_complete = "3.0.6"
colored = "2.0.0"
discord-rich-presence = "0.1.8"

[dependencies.clap]
version = "3.0.14"
features = ["derive", "cargo", "std"]
