[package]
name = "discordrpc"
description = "Fast Discord RPC Client written in Rust"
license = "BSD-3-Clause"
authors = ["MedzikUser <nivua1fn@duck.com>"]
homepage = "https://github.com/MedzikUser/discord-rpc"
repository = "https://github.com/MedzikUser/discord-rpc.git"
keywords = ["discord", "discord-rpc", "discordrpc", "discord-rich-presence", "discord-rpc-client"]
categories = ["command-line-utilities"]
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'
codegen-units = 1

[dependencies]
better-panic = "0.3.0"
clap_complete = "3.0.6"
colored = "2.0.0"
discord-rich-presence = "0.1.8"
ctrlc = "3.2.1"

[dependencies.clap]
version = "3.0.14"
features = ["derive", "cargo", "std"]
